# Generated by Django 2.1 on 2023-01-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0010_auto_20200816_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.AddField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(choices=[('text', 'None'), ('Markup', 'markup'), ('html', 'html'), ('CSS', 'css'), ('C-like', 'clike'), ('JavaScript', 'javascript, js'), ('Arduino', 'arduino'), ('Bash', 'bash, shell'), ('BASIC', 'basic'), ('C', 'c'), ('C#', 'csharp, cs, dotnet'), ('Cpp', 'cpp'), ('CoffeeScript', 'coffeescript, coffee'), ('CMake', 'cmake'), ('Clojure', 'clojure'), ('Django/Jinja2', 'django, jinja2'), ('Docker', 'docker, dockerfile'), ('Git', 'git'), ('GameMaker Language', 'gml, gamemakerlanguage'), ('Go', 'go'), ('GraphQL', 'graphql'), ('Groovy', 'groovy'), ('Haml', 'haml'), ('HTTP', 'http'), ('Icon', 'icon'), ('Java', 'java'), ('JavaDoc', 'javadoc'), ('JSDoc', 'jsdoc'), ('JSON', 'json'), ('JSONP', 'jsonp'), ('JSON5', 'json5'), ('Kotlin', 'kotlin'), ('LaTeX', 'latex, tex, context'), ('Latte', 'latte'), ('Less', 'less'), ('LiveScript', 'livescript'), ('Lua', 'lua'), ('Makefile', 'makefile'), ('Markdown', 'markdown, md'), ('MATLAB', 'matlab'), ('nginx', 'nginx'), ('Objective-C', 'objectivec'), ('OpenCL', 'opencl'), ('Parser', 'parser'), ('Pascal', 'pascal, objectpascal'), ('Perl', 'perl'), ('PHP', 'php'), ('PL/SQL', 'plsql'), ('PowerShell', 'powershell'), ('Pug', 'pug'), ('Python', 'python, py'), ('R', 'r'), ('React JSX', 'jsx'), ('React TSX', 'tsx'), ('Regex', 'regex'), ('Ruby', 'ruby, rb'), ('Rust', 'rust'), ('SAS', 'sas'), ('Sass (Sass)', 'sass'), ('Sass (Scss)', 'scss'), ('Scala', 'scala'), ('SQL', 'sql'), ('Stylus', 'stylus'), ('Swift', 'swift'), ('Twig', 'twig'), ('TypeScript', 'typescript, ts'), ('Velocity', 'velocity'), ('vim', 'vim'), ('Visual Basic', 'visual-basic, vb'), ('Wiki markup', 'wiki'), ('YAML', 'yaml, yml'), ('Zig', 'zig')], default='text', max_length=18),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
